backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/assets/img" # Where media files will be stored
public_folder: "/assets/img" # Where the media files can be accesed from the server
publish_mode: editorial_workflow # For Drafts

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featuredpost", name: "featuredpost", widget: "boolean"}
      - {label: "Featuredimage", name: "featuredimage", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "events" 
    label: "Events" 
    folder: "content/events" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Featuredpost", name: "featuredpost", widget: "boolean"}
      - {label: "Featuredimage", name: "featuredimage", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "about" 
    label: "About" 
    folder: "content/about" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Img", name: "img", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "sewa" 
    label: "Sewa" 
    folder: "content/sewa" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Img", name: "img", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "ebazaar" 
    label: "E-Bazaar" 
    folder: "content/ebazaar" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Img", name: "img", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "businesslisting" 
    label: "Business Listing" 
    folder: "content/businessList" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Full Name", name: "fullName", widget: "string"}
      - {label: "Business Name", name: "businessName", widget: "string"}
      - {label: "Hobby", name: "interestHobby", widget: "string"}
      - {label: "Contact", name: "contact", widget: "number"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Address", name: "address", widget: "string"}
      - {label: "State", name: "state", widget: "string"}
      - {label: "City", name: "city", widget: "string"}
      - {label: "Pincode", name: "pincode", widget: "number"}
      - {label: "Business Description", name: "businessDescription", widget: "string"}
      - {label: "Business Location", name: "businessLocation", widget: "string"}
      - {label: "Website Link", name: "webpageUrl", widget: "string"}
      - {label: "FaceBook Link", name: "facebook", widget: "string"}
      - {label: "Instagram Link", name: "instagramId", widget: "string"}

  - name: "home" 
    label: "Home" 
    folder: "content/home" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "img", widget: "string"}
      - {label: "Greeting Heading", name: "greetingHeading", widget: "string"}
      - {label: "Greeting Descripition", name: "greetingDescripition", widget: "string"}

  - name: "testimonials" 
    label: "Testimonials" 
    folder: "content/testimonials" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Name", name: "name", widget: "string"}
      - {label: "About", name: "title", widget: "string"}
      - {label: "Descripition", name: "desc", widget: "string"}
      - {label: "Image", name: "img", widget: "string"}

  - name: "carousels" 
    label: "Carousels" 
    folder: "content/carousel" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "img", widget: "string"}

  - name: "catering-and-food" 
    label: "Catering and Food" 
    folder: "content/stalls/catering-and-food" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - {label: "Stall Number", name: "stall_no", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Representation", name: "representation", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Product", name: "product", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Email1", name: "email1", widget: "string"}
      - {label: "contact", name: "contact", widget: "number"}
      - {label: "Contact1", name: "contact1", widget: "number"}
      - {label: "Website Link", name: "site", widget: "string"}
      - {label: "Youtube Link", name: "youtube_link", widget: "string"}
      - {label: "FaceBook Link", name: "fb", widget: "string"}
      - {label: "Instagram Link", name: "insta", widget: "string"}


  - name: "clothing" 
    label: "Clothing" 
    folder: "content/stalls/clothing" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - {label: "Stall Number", name: "stall_no", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Representation", name: "representation", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Product", name: "product", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Email1", name: "email1", widget: "string"}
      - {label: "contact", name: "contact", widget: "number"}
      - {label: "Contact1", name: "contact1", widget: "number"}
      - {label: "Website Link", name: "site", widget: "string"}
      - {label: "Youtube Link", name: "youtube_link", widget: "string"}
      - {label: "FaceBook Link", name: "fb", widget: "string"}
      - {label: "Instagram Link", name: "insta", widget: "string"}

  - name: "decorative-and-gift-items" 
    label: "Decorative and Gift items" 
    folder: "content/stalls/decorative-and-gift-items" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - {label: "Stall Number", name: "stall_no", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Representation", name: "representation", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Product", name: "product", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Email1", name: "email1", widget: "string"}
      - {label: "contact", name: "contact", widget: "number"}
      - {label: "Contact1", name: "contact1", widget: "number"}
      - {label: "Website Link", name: "site", widget: "string"}
      - {label: "Youtube Link", name: "youtube_link", widget: "string"}
      - {label: "FaceBook Link", name: "fb", widget: "string"}
      - {label: "Instagram Link", name: "insta", widget: "string"}

  - name: "decorative-items" 
    label: "Decorative Items" 
    folder: "content/stalls/decorative-gift-items" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - {label: "Stall Number", name: "stall_no", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Representation", name: "representation", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Product", name: "product", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Email1", name: "email1", widget: "string"}
      - {label: "contact", name: "contact", widget: "number"}
      - {label: "Contact1", name: "contact1", widget: "number"}
      - {label: "Website Link", name: "site", widget: "string"}
      - {label: "Youtube Link", name: "youtube_link", widget: "string"}
      - {label: "FaceBook Link", name: "fb", widget: "string"}
      - {label: "Instagram Link", name: "insta", widget: "string"}

  - name: "eco-friendly-and-furnishings" 
    label: "Eco-friendly and Furnishings" 
    folder: "content/stalls/eco-friendly-and-furnishings" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - {label: "Stall Number", name: "stall_no", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Representation", name: "representation", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Product", name: "product", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Email1", name: "email1", widget: "string"}
      - {label: "contact", name: "contact", widget: "number"}
      - {label: "Contact1", name: "contact1", widget: "number"}
      - {label: "Website Link", name: "site", widget: "string"}
      - {label: "Youtube Link", name: "youtube_link", widget: "string"}
      - {label: "FaceBook Link", name: "fb", widget: "string"}
      - {label: "Instagram Link", name: "insta", widget: "string"}

  - name: "jewellery" 
    label: "Jewellery" 
    folder: "content/stalls/jewellery" 
    create: true 
    slug: "{{slug}}" 
    fields:
      - {label: "Stall Number", name: "stall_no", widget: "string"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Representation", name: "representation", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Product", name: "product", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Email1", name: "email1", widget: "string"}
      - {label: "contact", name: "contact", widget: "number"}
      - {label: "Contact1", name: "contact1", widget: "number"}
      - {label: "Website Link", name: "site", widget: "string"}
      - {label: "Youtube Link", name: "youtube_link", widget: "string"}
      - {label: "FaceBook Link", name: "fb", widget: "string"}
      - {label: "Instagram Link", name: "insta", widget: "string"}

  # - label: FAQS
  #   name: faqs
  #   widget: list
  #   fields: 
  #     - label: FAQ
  #       name: faq
  #       widget: object
  #       fields:
  #         - { label: Question, name: question, widget: string, default: "Question" }
  #         - { label: Answer, name: answer, widget: string, default: "Answer" }
